export const PROJECTS = [
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
  {
    title: "Portfolio",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
    link: "https://acme.com",
    contribution: "FE (100%)",
    img_src: "/images/projects/portfolio.png",
  },
];
